config/routes.rb
Riddleqlist2::Application.routes.draw do
  resources :roles

  resources :races

  resources :professions

  resources :talents

  resources :guilds

  resources :specs

  resources :characters

   root :to => 'characters#index'

end

app/models/boss.rb
class Boss < ActiveRecord::Base
  belongs_to :raid
  has_and_belongs_to_many :character
  attr_accessible :name, :raid_id
  validates :name, :presence => true, :uniqueness => true
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :level, :numericality => { :only_integer => true }, :presence => true
  belongs_to :spec
  belongs_to :primary_talent, :class_name => "Talent"
  belongs_to :secondary_talent, :class_name => "Talent"
  belongs_to :guild
  has_and_belongs_to_many :role
  has_and_belongs_to_many :boss
  belongs_to :race
  attr_accessible :name, :spec, :primary_talent_id, :secondary_talent_id, :guild_id, :race, :race_id, :spec_id, :notes, :rating, :id_bnet, :level, :role_ids, :boss_ids
end

app/models/characters_boss.rb
class CharactersBoss < ActiveRecord::Base
  belongs_to :character
  belongs_to :boss
  # attr_accessible :title, :body
end

app/models/characters_role.rb
class CharactersRole < ActiveRecord::Base
  belongs_to :character
  belongs_to :role
  # attr_accessible :title, :body
end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
end

app/models/expansion.rb
class Expansion < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true

end

app/models/guild.rb
class Guild < ActiveRecord::Base
  attr_accessible :name, :id_bnet
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  attr_accessible :level, :name
end

app/models/race.rb
class Race < ActiveRecord::Base
  attr_accessible :name, :id_bnet
  validates :name, :presence => true, :uniqueness => true
  validates :id_bnet, :numericality => { :only_integer => true }, :presence => true, :uniqueness => true
end

app/models/raids.rb
class Raids < ActiveRecord::Base
  belongs_to :location
  belongs_to :expansion

  attr_accessible :level, :name, :expansion_id, :location_id
  # :name can not be unique becuase they re-use bosses in newer raids, esp cata
  validates :name, :presence => true
  validates :level, :numericality => { :only_integer => true }, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :character
  attr_accessible :name
end

app/models/spec.rb
class Spec < ActiveRecord::Base
  attr_accessible :name, :id_bnet
  validates :name, :presence => true, :uniqueness => true
  validates :id_bnet, :numericality => { :only_integer => true }, :presence => true, :uniqueness => true
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  attr_accessible :name, :spec_id
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
  @character = Character.new
	@specs = Spec.order(:name)
	@talents = Talent.order(:name)
	@races = Race.order(:name)
	@guilds = Guild.order(:name)
  @roles = Role.all
  @raids = Raids.all
  @expansions = Expansion.all
  @bosses = Boss.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
  @character = Character.find(params[:id])
	@specs = Spec.order(:name)
	@talents = Talent.order(:name)
	@races = Race.order(:name)
  @roles = Role.all
	@guilds = Guild.order(:name)
  @raids = Raids.all
  @expansions = Expansion.all
  @bosses = Boss.all
  end

def import_from_battlenet
    Battlenet.fail_silently = true
    bnet = Battlenet.new :us 
    puts "#{@character.name.capitalize}"
    toon = bnet.character 'Moonrunner', "#{@character.name.capitalize}", :fields => "guild,talents,class,race"
    unless toon["name"].nil?
      toon_spec = Spec.find_by_id_bnet(toon['class'])
      @character.spec_id = toon_spec.id
      toon_race = Race.find_by_id_bnet(toon['race'])
      @character.race_id = toon_race.id
      toon_guild = Guild.find_or_create_by_name("#{toon['guild']['name']}")
      @character.guild_id = toon_guild.id
      @character.level = "#{toon['level']}"
      puts "CLASS ====== #{toon_spec.name}"
      puts "RACE ======= #{toon_race.name}"
      puts "LEVEL ====== #{toon['level']}"
      puts "GUILD ====== #{toon['guild']['name']}"
      puts "TALENTS ==== #{toon['talents']}"
      toon['talents'].each_with_index do |t,i|
        if i == 0
          puts "PRIMARY TALENT ======= #{t['spec']['name']}"
          toon_talent = Talent.find_by_name("#{t['spec']['name']}")
          @character.primary_talent_id = toon_talent.id
        elsif i == 1
          puts "SECONDARY TALENT ======= #{t['spec']['name']}}"
          toon_talent = Talent.find_by_name("#{t['spec']['name']}")
          @character.secondary_talent_id = toon_talent.id
        end  
      end
    else
      @character.errors.add(:name, "Character not found on battlenet")
    end


end
  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])
    @specs = Spec.order(:name)
    @talents = Talent.order(:name)
    @races = Race.order(:name)
    @guilds = Guild.order(:name)
    @roles = Role.all
    @raids = Raids.all
    @expansions = Expansion.all
    @bosses = Boss.all

    respond_to do |format|
      if params[:import]
        import_from_battlenet
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      else
        if @character.save
            format.html { redirect_to @character, notice: 'Character was successfully created.' }
          format.json { render json: @character, status: :created, location: @character }
        else
          format.html { render action: "new" }
          format.json { render json: @character.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])
    @specs = Spec.order(:name)
    @talents = Talent.order(:name)
    @races = Race.order(:name)
    @roles = Role.all
    @guilds = Guild.order(:name)
    @raids = Raids.all
    @expansions = Expansion.all
    @bosses = Boss.all

    respond_to do |format|
      if params[:import]
        import_from_battlenet
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      else
        if @character.update_attributes(params[:character])
          format.html { redirect_to @character, notice: 'Character was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @character.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/characters/_expansion.html.erb
  <div class="field">
    <%= f.label expansion.name %><br />
   		<% @raids.each do |raid| %>
   			<% if expansion.id == raid.expansion.id %>
   				<%= raid.name %> 
   				:
   				<% @bosses.each do |bosse| %>
   					<% if raid.id == bosse.raid_id %>
   					<%= check_box_tag "character[boss_ids][]",bosse.id %> 
   						<%= bosse.name %>
   					<% end %>
   				<% end %>
   			</br>
   			<% end %>
   		<% end %>
  </div>

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Update from BattleNet", :name => "import" %>
  </div>
  <%= render :partial => 'level', :locals => {:f => f} %>
  <%= render :partial => 'spec', :locals => {:f => f} %>
  <%= render :partial => 'guild', :locals => {:f => f} %>
  <%= render :partial => 'race', :locals => {:f => f} %>
  <%= render :partial => 'role', :locals => {:f => f} %>
  <% @expansions.reverse.each do |e| %>
    <%= render :partial => 'expansion', :locals => {:f => f, :expansion => e} %>
  <% end %>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, (1..10).map {|r| [r,r] } %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/_guild.html.erb
  <div class="field">
    <%= f.label :guild %><br />
    <%= f.select :guild_id, @guilds.map {|r| [r.name,r.id] } %>
  </div>

app/views/characters/_level.html.erb
  <div class="field">
    <%= f.label :level %><br />
    <%= f.select :level, (1..90).reverse_each.map {|r| [r,r]} %>
  </div>

app/views/characters/_race.html.erb
  <div class="field">
    <%= f.label :race %><br />
    <%= f.select :race_id, @races.map {|r| [r.name,r.id] } %>
  </div>

app/views/characters/_role.html.erb
<%= f.label "Roles" %><br/>
<% @roles.each do |r| %>
	<%= check_box_tag "character[role_ids][]",r.id, @character.role.include?(r) %>
	<%= r.name %>
<% end %>

app/views/characters/_spec.html.erb
  <div class="field">
    <%= f.label :spec %><br />
    <%= f.select :spec_id, @specs.map {|r| [r.name,r.id] } %>
  </div>
  <div class="field">
    <%= f.label :primary_talent %><br />
    <%= f.select :primary_talent_id, @talents.map {|r| [r.name,r.id] } %>
  </div>
  <div class="field">
    <%= f.label :secondary_talent %><br />
    <%= f.select :secondary_talent_id, @talents.map {|r| [r.name,r.id] } %>
  </div>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Level</th>
    <th>Spec</th>
    <th>Primary talent</th>
    <th>Secondary talent</th>
    <th>Guild</th>
    <th>Race</th>
    <th>Rating</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= link_to character.name, "http://us.battle.net/wow/en/character/moonrunner/#{character.name.capitalize}/simple" %></td>
    <td><%= character.level %></td>
    <td><%= character.spec.name %></td>
    <td><%= character.primary_talent.name %></td>
    <td><%= character.secondary_talent.name %></td>
    <td><%= character.guild.name %></td>
    <td><%= character.race.name %></td>
    <td><%= character.rating %></td>
    <td><%= truncate(character.notes, :length => 60) %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Level:</b>
  <%= @character.level %>
</p>

<p>
  <b>Spec:</b>
  <%= @character.spec.name %>
</p>

<p>
  <b>Primary talent:</b>
  <%= @character.primary_talent.name %>
</p>

<p>
  <b>Secondary talent:</b>
  <%= @character.secondary_talent.name %>
</p>

<p>
  <b>Guild:</b>
  <%= @character.guild.name %>
</p>

<p>
  <b>Race:</b>
  <%= @character.race.name %>
</p>
<p>
  <b>Rating:</b>
  <%= @character.rating %>
</p>
<p>
  <b>Notes:</b>
  <%= @character.notes %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>