config/routes.rb
Riddleqlist2::Application.routes.draw do
  resources :roles

  resources :races

  resources :professions

  resources :talents

  resources :guilds

  resources :specs

  resources :characters

   root :to => 'characters#index'

end

app/models/boss.rb
class Boss < ActiveRecord::Base
  belongs_to :raid
  has_and_belongs_to_many :character
  attr_accessible :name, :raid_id
  validates :name, :presence => true, :uniqueness => true
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :level, :numericality => { :only_integer => true }, :presence => true
  belongs_to :spec
  belongs_to :primary_talent, :class_name => "Talent"
  belongs_to :secondary_talent, :class_name => "Talent"
  belongs_to :guild
  has_and_belongs_to_many :role
  has_and_belongs_to_many :boss
  belongs_to :race
  attr_accessible :name, :spec, :primary_talent_id, :secondary_talent_id, :guild_id, :race, :race_id, :spec_id, :notes, :rating, :id_bnet, :level, :role_ids, :boss_ids
end

app/models/characters_boss.rb
class CharactersBoss < ActiveRecord::Base
  belongs_to :character
  belongs_to :boss
  # attr_accessible :title, :body
end

app/models/characters_role.rb
class CharactersRole < ActiveRecord::Base
  belongs_to :character
  belongs_to :role
  # attr_accessible :title, :body
end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
end

app/models/expansion.rb
class Expansion < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true

end

app/models/guild.rb
class Guild < ActiveRecord::Base
  attr_accessible :name, :id_bnet
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  attr_accessible :level, :name
end

app/models/race.rb
class Race < ActiveRecord::Base
  attr_accessible :name, :id_bnet
  validates :name, :presence => true, :uniqueness => true
  validates :id_bnet, :numericality => { :only_integer => true }, :presence => true, :uniqueness => true
end

app/models/raids.rb
class Raids < ActiveRecord::Base
  belongs_to :location
  belongs_to :expansion

  attr_accessible :level, :name, :expansion_id, :location_id
  # :name can not be unique becuase they re-use bosses in newer raids, esp cata
  validates :name, :presence => true
  validates :level, :numericality => { :only_integer => true }, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :character
  attr_accessible :name
end

app/models/spec.rb
class Spec < ActiveRecord::Base
  attr_accessible :name, :id_bnet
  validates :name, :presence => true, :uniqueness => true
  validates :id_bnet, :numericality => { :only_integer => true }, :presence => true, :uniqueness => true
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  attr_accessible :name, :spec_id
end

app/controllers/specs_controller.rb
class SpecsController < ApplicationController
  # GET /specs
  # GET /specs.json
  def index
    @specs = Spec.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specs }
    end
  end

  # GET /specs/1
  # GET /specs/1.json
  def show
    @spec = Spec.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spec }
    end
  end

  # GET /specs/new
  # GET /specs/new.json
  def new
    @spec = Spec.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spec }
    end
  end

  # GET /specs/1/edit
  def edit
    @spec = Spec.find(params[:id])
  end

  # POST /specs
  # POST /specs.json
  def create
    @spec = Spec.new(params[:spec])

    respond_to do |format|
      if @spec.save
        format.html { redirect_to @spec, notice: 'Spec was successfully created.' }
        format.json { render json: @spec, status: :created, location: @spec }
      else
        format.html { render action: "new" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specs/1
  # PUT /specs/1.json
  def update
    @spec = Spec.find(params[:id])

    respond_to do |format|
      if @spec.update_attributes(params[:spec])
        format.html { redirect_to @spec, notice: 'Spec was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specs/1
  # DELETE /specs/1.json
  def destroy
    @spec = Spec.find(params[:id])
    @spec.destroy

    respond_to do |format|
      format.html { redirect_to specs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/specs/_form.html.erb
<%= form_for(@spec) do |f| %>
  <% if @spec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spec.errors.count, "error") %> prohibited this spec from being saved:</h2>

      <ul>
      <% @spec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specs/edit.html.erb
<h1>Editing spec</h1>

<%= render 'form' %>

<%= link_to 'Show', @spec %> |
<%= link_to 'Back', specs_path %>

app/views/specs/index.html.erb
<h1>Listing specs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specs.each do |spec| %>
  <tr>
    <td><%= spec.name %></td>
    <td><%= link_to 'Show', spec %></td>
    <td><%= link_to 'Edit', edit_spec_path(spec) %></td>
    <td><%= link_to 'Destroy', spec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spec', new_spec_path %>

app/views/specs/new.html.erb
<h1>New spec</h1>

<%= render 'form' %>

<%= link_to 'Back', specs_path %>

app/views/specs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @spec.name %>
</p>


<%= link_to 'Edit', edit_spec_path(@spec) %> |
<%= link_to 'Back', specs_path %>